# Welcome to Jekyll!

# Site Settings
locale                   : "en-US"
title                    : "Michele Croci"
title_separator          : "-"
name                     : &name "Michele Croci"
description              : &description "Agronomist | EO Data scientist 🌱🛰"
url                      : https://MCroci.github.io
baseurl                  : ""
repository               : "MCroci/MCroci.github.io"
teaser                   : 
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : 
  facebook:
    colorscheme          : "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  path                   : 

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "Croci93"
og_image                 : 
social:
  type                   : Person
  name                   : Michele Croci
  links:
    - https://github.com/MCroci
    - https://twitter.com/Croci93
    - https://scholar.google.com/citations?user=FUxxRLYAAAAJ&hl=en
    - https://orcid.org/0000-0001-7356-2774
    - https://www.researchgate.net/profile/Michele-Croci/
    - https://instagram.com/michele.croci

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : 

# Site Author
author:
  name             : "Michele Croci"
  avatar           : "logoRemoteSensingTeam.png"
  bio              : "Agronomist | EO Data scientist 🌱🛰"
  location         : "Piacenza, Italy"
  googlescholar    : "https://scholar.google.com/citations?user=FUxxRLYAAAAJ&hl=en"
  email            : "michele.croci@unicatt.it"
  researchgate     : "https://www.researchgate.net/profile/Michele-Croci/"
  github           : "MCroci"
  instagram        : "michele.croci"
  orcid            : "https://orcid.org/0000-0001-7356-2774"
  twitter          : "Croci93"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Europe/Rome

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise"

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
